### ISSUE TITLE
Where is the configuration?

### ISSUE THREAD

**Issue by f-kessler** [Scriptkiddi/anknotes#3]
I'm trying to use this plug-in, but unfortunately I failed to change the settings. Currently there is no config file like in the original version from brumar. How can I change the tags that will be imported from evernote?
Please advise.

**Comment by Scriptkiddi** [comment]
hey sorry for the late reply the configuration is tools>preferences at the bottom to allow a better way to edit the config

**Comment by f-kessler** [comment]
My bad! I didn't have recognized that the config is integrated into the regular preferences menu. I should have read the "How to use it" part of the readme more accurate...
Thanks very much!
