### ISSUE TITLE
duplicates of changed and viewed cards in Anki

### ISSUE THREAD

**Issue by f-kessler** [Scriptkiddi/anknotes#4]
The first import seems to work well and subsequent imports are working too, until I start editing the cards or just viewing them in Anki. After the next import from evernote, I have duplicates of the edited or viewed cards in the deck. Editing the note in evernote does not cause duplicates. Only editing in Anki cause this.
I'm no programmer. Maybe scriptkiddi or someone else could help me. Thanks!

**Comment by Scriptkiddi** [comment]
hey i will try to get it tested this week what system are you using btw?

**Comment by f-kessler** [comment]
I'm using Ubuntu 14.04. Thank you!

**Comment by Scriptkiddi** [comment]
hey ok so as a short question is it working on your pc because it keeps repromting the access code and crashes after it

**Comment by Scriptkiddi** [comment]
well nevermind i was really tired just noticed i was running on an old branch never mind that i still have a wired timeout issue with evernote when im pulling cards im going to take antoher look tomorrow

**Comment by Scriptkiddi** [comment]
hey so got i running again apperntly it had something todo with my connection.
But now back to your problem I could not replicate it with viewing or editing
can you please explain what steps you took exactly

**Comment by f-kessler** [comment]
This is what I'm doing or what I've done:
- downloaded the zip from your project page. 
- put the files into the addon folder
- configured the import tag and the default deck in the preferences
- pulled the cards from evernote
- go to browse and filtered for the imported deck
- reviewed some cards (clicked on them without changing the contents) or changed one or more cards
- closed the browse window
- pulled the cards from evernote again and receive duplicate cards for the reviewed ones

I did the same on a windows 7 machine and had the exact same issue.

**Comment by Scriptkiddi** [comment]
just to make sure you downloaded the zip file from this git repo?
