### ISSUE TITLE
Anki Hangs when Importing from Evernote

### ISSUE THREAD

**Issue by aip1000** [Scriptkiddi/anknotes#6]
Hi,
Thanks again for your great work on this plugin. It loads fine, and I'm able to run the "Import from Evernote" command. Unfortunately, running the command causes Anki to hang. This is with an Evernote tag containing ~60 notes. The addon works perfectly with a *different* tag containing ~20 notes. Anki hangs but eventually successfully imports for a different Evernote tag containing 30 notes. I let Anki run for about 20 minutes each time before force-closing it.

Anything I could do to help you debug? Unfortunately I don't know Python so I can't delve into the code

**Comment by aip1000** [comment]
Here's an error that was thrown the last time I tried importing all my notes (440 in total). Does this mean your script is executing too many requests to Evernote? FYI I have tried importing 3-4 times and have only got this error once.

  File "C:\Users\_HIDDEN_\Documents\Anki\addons\anknotes\evernote\edam\notestore\NoteStore.py", line 4172, in recv_getNote
    raise result.systemException
anknotes.evernote.edam.error.ttypes.EDAMSystemException: EDAMSystemException(errorCode=19, rateLimitDuration=1576, _message=None)

**Comment by aip1000** [comment]
Odd... Now I'm getting this error immediately upon starting the Import. It happens everytime, even for tags that I've successfully imported before:

  File "C:\Users\_HIDDEN_\Documents\Anki\addons\anknotes\evernote\edam\userstore\UserStore.py", line 3239, in read
    self.systemException = evernote.edam.error.ttypes.EDAMSystemException()
NameError: global name 'evernote' is not defined

**Comment by aip1000** [comment]
So I looked into the two errors a bit. Error 1 is apparently because the Evernote API has a rate limit per hour per user. See https://dev.evernote.com/doc/articles/rate_limits.php. The page mentions some ways to efficiently use the API; I don't know if any of those suggestions would apply to your addon as I don't know Python enough to look at the code.

Since the addon initially syncs data, you can contact Evernote and request they enable "Initial Sync Boost" for your addon. This will allow unlimited calls during the first 24 hours after creating an authentication token.

As far as the second error, I have no idea.

Sorry for all the messages at once, but I hope it helps!

**Comment by Scriptkiddi** [comment]
Hey thanks for reporting the errors so first of
i did not write the code for the api requests that is still code brumar wrote I only added the front end to it but i will have a how he is querying the api but it might take me a few days

to the second error I think this could be because I messed with the api a bit and forgot to change that line back to what it was

**Comment by Scriptkiddi** [comment]
im going to close this one and open a new one with the api use
