### ISSUE TITLE
Tags Still Not Being Saved with Latest Commit

### ISSUE THREAD

**Issue by aip1000** [Scriptkiddi/anknotes#9]
Hi there, the force-crash was fixed with the latest commit, but the tags from Evernote are still not being saved. When browsing the imported deck, I only see the "Default Tag" from the Preferences. Also I double-checked and I do have "Keep Evernote Tags" enabled in the preferences

**Comment by Scriptkiddi** [comment]
my bad i did a string comparison but anki upgraded the database some while ago to work with booleans so it should be working now let me know if it does

**Comment by aip1000** [comment]
Oh nice, so the tags are now being saved. However, I don't think multiple tags are working properly.  If I have multiple tags in Evernote, they are not being saved as individual tags in Anki. For example, say I have a note in Evernote with the tags "Cardiology" and "Pharmacology", instead of having two different tags in Anki, Anki has one tag "Cardiology,Pharmacology". 

I'm guessing you would have to iterate through each of the tags Evernote's API supplies by splitting the string by ",", then individually add each tag to Anki. Again, wish I knew Python so I could make some of these changes for you!

**Comment by aip1000** [comment]
So I delved into the code a bit and fixed the error - with a small caveat.  Multiple tags are being added, except tags with spaces in them are being treated as separate tags. For example the single tag "Cardiovascular System" is being added as two separate tags, "Cardiovascular" and "System"

Please see the modified code here: http://pastebin.com/MN5GWThj

Note that in addition to the tag creation changes, I also commented out a notification when an individual note is added, just because Anki hangs when the plugin runs, and you cannot see the notification anyway.

**Comment by aip1000** [comment]
I made a change and the tags import now works perfectly. See the pastebin link above for the code. Thanks again for your work!
